### ISSUE TITLE
VideoEncoder.configure doesn't work and "stop" the code located after its call

### ISSUE THREAD

**Issue by tlecoz** [WICG/web-codecs#81]
I'm trying to implement a part of "live streaming upload" example located here
https://github.com/WICG/web-codecs/blob/master/explainer.md 

But my code is "stopped" immediatly after I call VideoEncoder.configure 
For example, if I do 

```
 let stream = canvas.captureStream();
 let videoTrack = stream.getVideoTracks()[0];
 let videoTrackReader = new window["VideoTrackReader"](videoTrack);

let onVideoDecode = (encodedChunk)=>{
   console.log("onVideoDecoded:", encodedChunk);
}
let onVideoError = (error)=>{
    console.log("onVideoError:",error);
}

let encoder = new window["VideoEncoder"]({
   output:onVideoDecode,
   error:onVideoError
})

console.log("before configure");
encoder.configure({
   codec:"vp9",
   width:1920,
   height:1080
});
console.log("after configure"); 
```

My last console.log "after configure"  is never called , and the rest of my code below encoder.configure neither. 

(I'm working with nw.js and I'm using nwjs-sdk-v0.49.0-beta1-win-x64 based on chrome 86.0.4240.22 )

**Comment by chcunningham** [comment]
You're configure call is throwing an exception. You can see it [caught in this fiddle](https://jsfiddle.net/d3et49nm/2/).

```"caught:TypeError: Failed to execute 'configure' on 'VideoEncoder': required member framerate is undefined."```

You'll also want to replace "vp9" with the "vp09.00.10.08" style string. We don't allow the old vp9 style because its ambiguous about critical details like the profile. More [info here](https://wicg.github.io/web-codecs/#config-codec-string).

**Comment by tlecoz** [comment]
Thank you !
