### ISSUE TITLE
Support VideoTrackWriter

### ISSUE THREAD

**Issue by daijh** [WICG/web-codecs#91]
VideoTrackWriter is not defined in specification, and code is disable in Chrome.

[https://wicg.github.io/web-codecs/](https://wicg.github.io/web-codecs/)

**Comment by chcunningham** [comment]
This is still in our plans. We're discussing possible API shapes (including the disabled one that's already coded).

**Comment by aboba** [comment]
VideoTrackWriter seems similar in function to [Insertable Streams Raw Media](https://github.com/alvestrand/mediacapture-insertable-streams).  How do the two APIs relate?

**Comment by tguilbert-google** [comment]
Currently, `VideoTrackReader` is using callbacks and `VideoTrackWriter` is using streams. We will make sure both are callback or streams based before WebCodecs ship.

`VTR` and `VTW` do not use Control Signals, unlike the proposal. Developpers are encouraged to directly listen to `mute`/`unumute`/`ended` from the `MediaStreamTrack` instead, for example. However, the proposal mentions that Control Signals can be ignored. This means we could delete `VTR`/`VTW`, and use the `TrackProcessor`/`TrackGenerator` from that proposal, while ignoring the control signals.

Another option is to make VTW use callbacks as well. The simplicity of the API is appealing, and `VTR`/`VTW` could easily be wrapped into a custom stream. Users could still use the `TrackProcessor`/`TrackGenerator` when they ship.

I am aware of two small potential gotchas with streams:
- `ReadableStream.tee()` wouldn't work with `VideoFrames`, because they need to be clone rather than copied. IDK if this is actually an issue for most users, and there is likely a way to fix this.
- A `ReadableStream<VideoFrame>` has (or should have) an internal queue size of 1 (due to limited HW frame pool sizes). This means that the first frame read from the stream might be stale, if the `MediaStreamTrack` emitted multiple frames before we started reading. If we are too slow to read, we might also drop frames.

There is also a benefit to streams in workers, if the underlying stream can be re-bound to the right thread (which is [currently being discussed](https://docs.google.com/document/d/19WpamKCysWHYGA6jIrlwZIYxhBrsHCDHYNd98Zl1u5w)) to avoid IO->Main->Worker thread hops of `VideoFrames` coming from a webcam, and instead only having IO->Worker.

The current direction is to convert `VideoTrackWriter` to use callbacks, which won't bar developers from using whatever comes out of the [Insertable Stream Raw Media](https://w3c.github.io/mediacapture-insertable-streams/) proposal.

**Comment by tguilbert-google** [comment]
I haven't fully investigated backpropagation or lack thereof.

**Comment by daijh** [comment]
The intention of this issue is to provide an alternative presentation path \<video\> to Canvas.

Presentation by Canvas enables user to processe VideoFrame with WebGL to implement Funny hats, Background removal and many other uages.

But in non video processing usage, presentation by Canvas consumes more power than \<video\>.
- Presentation by Canvas: multiple YUV->RGB, RGB->RGB conversions.<br>VideoFrame->ImageBitmap->DrawImage()
- Presentation by \<video\>: the yuv VideoFrame is able to render to display hardware overlay directly without any intermedia conversion.

| 1280x720 VideoFrame 10 fps | Canvas  | \<video\> |
|----------------------------|---------|-----------|
| Power                      | 7377 mw | 6685 mw   |

<br>Both mediacapture-insertable-streams and VideoTrackerWriter proposals seem to meet this purpose.

**Comment by daijh** [comment]
Close the issue as MediaStreamTrackProcessor/MediaStreamTrackGenerator are recommended.

Deprecate VideoTrackReader #131
